name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  quality-code:
    name: Quality-Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11' 
      - name: Install Tox
        run: pip install tox
      - name: Run Tox Scan
        run: tox -e py
      - name: Display Coverage Report Before
        run: cat coverage.xml
      - name: Override Coverage Source Path for Sonar
        run: sed -i 's|<source>/home/runner/work/py-microservice-poc/py-microservice-poc/app</source>|<source>py-microservice-poc/app</source>|' coverage.xml
      - name: Display Coverage Report After
        run: cat coverage.xml
      - name: Run SonarCloud Scan
        if: always()
        uses: SonarSource/sonarcloud-github-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
