name: build-quality
on:
  push:
    branches:
      - main
    paths:
      - 'app/**/*.py'
      - 'tests/**/*.py'
      - 'requirements.txt'
      - 'tox.ini'
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  quality-code:
    name: Quality-Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Cache Tox dependencies
        id: cache-tox
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tox.ini') }}
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.11' 
      - name: Install Tox
        run: pip install tox
      - name: Run Tox Scan
        run: tox -e py
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
